name: Continuous Deployment

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
        echo Hello there!
        
      env:
        CI: true
        runs-on: ubuntu-latest
